#!/bin/bash

# Settings

NEOLOGD_DIR='/home/tao/mo2ka/mecab-ipadic-neologd'
IGO_JAR='/home/tao/mo2ka/igo-0.4.5.jar'

##########

getopts "n" not_remove_oldbuild

current_build=`ls -t ${NEOLOGD_DIR}/build/ | head -1`
${NEOLOGD_DIR}/bin/install-mecab-ipadic-neologd -a -n <<< 'no'
build_dir=`ls -t ${NEOLOGD_DIR}/build/ | head -1`

if [ "${current_build}" = "${build_dir}" ]; then
	echo -e "\nThere is no update of neologd dic" 1>&2
	exit 1
fi

echo -e "\nRenewed neologd dic"

igo_jar_basename=`basename $IGO_JAR`
echo -e "make igo dic\nUsing ${build_dir}"
cd "${NEOLOGD_DIR}/build/${build_dir}"
cp $IGO_JAR .
java -Xmx5G -cp $igo_jar_basename net.reduls.igo.bin.BuildDic ../../../neologd . "utf-8"
rm $igo_jar_basename

if [ "${not_remove_oldbuild}" != "n" ]; then
	rm -rf ${NEOLOGD_DIR}/build/$current_build && echo "Removed old neologd dic: `basename ${current_build}`"
fi

exit 0
